### PR TITLE
[SAC-246][CORE] Use current db name in current Spark session when Spark table information doesn't provide db name

### LINKED ISSUE #246: Current database should be used when Spark table information doesn't provide db name
If we call USE <db> and execute queries without specifying db explicitly, objects will be bound to such db, but tableIdentifier.database is `None`. SAC just provides "default" when it's `None` which makes table entity being matched to wrong database.

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

This patch proposes to use current DB name in current Spark session instead of `default` when Spark table information doesn't contain database name.

## How was this patch tested?

Modified UT. Without the change, `prepareEntity` fails to find table entity from "default" database.

Closes #246

### CODE REVIEW

File: spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala [hunk 1]
```diff
@@ -202,7 +202,7 @@ object CommandsHarvester extends AtlasEntityUtils with Logging {
 
   def prepareEntity(tableIdentifier: TableIdentifier): AtlasEntityWithDependencies = {
     val tableName = tableIdentifier.table
-    val dbName = tableIdentifier.database.getOrElse("default")
+    val dbName = tableIdentifier.database.getOrElse(SparkUtils.getCurrentDatabase)
```
Comment (arunmahadevan) [inline spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala]: Do we also need to worry about the case sensitivity? In the spark code I see it converts the DB name to lowercase based on the setting ([here](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/SessionCatalog.scala#L130)). Just wondering if something similar needs to be done.

Comment (HeartSaVioR) [reply spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala]: Good point. Spark also has similar code for what we're doing here, so we could follow with it:

https://github.com/apache/spark/blob/6a317c8f014557dfd60931bd1eac3f545520d939/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/SessionCatalog.scala#L403-L405

In fact, `currentDb` should have applied `formatDatabaseName` before assigning, so effectively we can just use it,

https://github.com/apache/spark/blob/6a317c8f014557dfd60931bd1eac3f545520d939/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/SessionCatalog.scala#L254-L267

but Spark calls `formatDatabaseName` anyway so ideal to follow their pattern.

Comment (ankuriitg) [reply spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala]: You are still planning to make this change for both tableName and dbName, right? And I am guessing you may have already made sure that everywhere we are using SparkUtils methods to find dbName and tableName, but I just wanted to call that out.

**Comment by arunmahadevan** [comment]
Thanks for addressing name formatting. LGTM.

File: spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala (hunk 1 above)
Comment (HeartSaVioR) [reply spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala]: Yes I found all accessing `tableIdentifier` and changed them via 1c070f3.

Comment (HeartSaVioR) [reply spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala]: I found this change is not outdated while talking with @ankuriitg - sorry I'll make the change quickly.

**Comment by HeartSaVioR** [comment]
Please take a look at latest commit as well. Thanks!
